version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./postgres_data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - POSTGRES_NAME=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_HOST=db
    depends_on:
      - db
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/static
    ports:
      - 7999:7999
    depends_on:
      - web
volumes:
  static_volume:
